version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"

    environment:
      - DB_USER=postgres
      - DB_NAME=supplierManagementDB
      - DB_PASSWORD=postgres
      - DB_HOST=db

    command: >
      sh -c " python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
      - static-media-data:/vol
    user: myuser

    depends_on:
      - db

  db:
    image: "postgres:15.1-alpine"
    restart: always
    hostname: db
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=supplierManagementDB
volumes:
  dev-db-data:
  static-media-data:

