# Generated by Django 4.1.6 on 2023-02-06 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_function_supplier_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='convertion_rate',
            new_name='conversion_rate',
        ),
    ]
