# Generated by Django 4.1.6 on 2023-02-06 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_pic_alter_supplier_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='supplier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.supplier'),
        ),
    ]
