# Generated by Django 4.1.6 on 2023-02-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_ingredient_function_ingredient_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
