# Generated by Django 4.1.6 on 2023-02-13 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_unit_conversion_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=10, max_digits=120),
        ),
        migrations.CreateModel(
            name='PicDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isoDocument', models.FileField(null=True, upload_to='')),
                ('gmpDocument', models.FileField(null=True, upload_to='')),
                ('haccpDocument', models.FileField(null=True, upload_to='')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isoDocument', models.FileField(null=True, upload_to='')),
                ('gmoDocument', models.FileField(null=True, upload_to='')),
                ('kosherDocument', models.FileField(null=True, upload_to='')),
                ('halalDocument', models.FileField(null=True, upload_to='')),
                ('msdsDocument', models.FileField(null=True, upload_to='')),
                ('tdsDocument', models.FileField(null=True, upload_to='')),
                ('coaDocument', models.FileField(null=True, upload_to='')),
                ('allergenDocument', models.FileField(null=True, upload_to='')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.supplier')),
            ],
        ),
    ]
