# Generated by Django 4.1.6 on 2023-02-13 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_unit_conversion_rate_picdocument_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PicDocument',
            new_name='SupplierDocument',
        ),
        migrations.RemoveField(
            model_name='ingredientdocument',
            name='supplier',
        ),
        migrations.AddField(
            model_name='ingredientdocument',
            name='ingredient',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.ingredient'),
            preserve_default=False,
        ),
    ]
